{% set version = "3.4.0" %}

package:
  name: freeglut
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/freeglut/files/freeglut/{{ version }}/freeglut-{{ version }}.tar.gz
  sha256: 3c0bcb915d9b180a97edaebd011b7a1de54583a838644dcd42bb0ea0c6f3eaec
  patches:
    - disable_autolink_windows.patch

build:
  number: 3
  skip: true  # [osx]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=freeglut
    # very good backwards compatibility
    - {{ pin_subpackage("freeglut", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                               # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
  host:
    - libglu                             # [linux]
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]
    - xorg-xproto                        # [linux]
  run:
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]

test:
  files:
    - test

  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - libglu                             # [linux]
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - xorg-libxfixes                     # [linux]

  commands:
    # Test includes.
    - test -d "${PREFIX}/include/GL"  # [linux]

      # Test libraries.
    - test ! -f "${PREFIX}/lib/libglut.a"   # [linux]
    - test -f "${PREFIX}/lib/libglut.so"    # [linux]
    - ldd "${PREFIX}/lib/libglut.so"        # [linux]

    # Test Windows includes and libraries.
    - if not exist %LIBRARY_INC%\\GL\\freeglut.h     exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_ext.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_std.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\glut.h         exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\freeglut.lib       exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\freeglut.dll       exit 1   # [win]

about:
  home: http://freeglut.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A GUI based on OpenGL.

extra:
  recipe-maintainers:
    - jakirkham
    - shadowwalkersb
    - wolfv
