appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CN3OjaRvuSqZjRB4CznlMLofjawgjARfalvN65ioUE8JTvY7b2NPy3lrVIQnNYlAMcFT0sMBTxsmMNa++dcYJI3CvD5vfVjZu+SHFCSZvlnGif5p4mCZKjd0+i/t/1FcmT6uhPFUNZhna6N3prA+vUqgJFbGTtTetvg+Neal3Vll3na06s22T3aD0heF80Qd7M498FHv1ghWHIsSSCDcQpiEwM0j0VPO9yeYHCIHuXMSpdBGBnjxNcZ1bpdExI0e2xQIJtbi9HbqjnGxHUZQrU6FrsLO+L+C3OVAw3C77cMtWjM7/tRgcB03tehs6s1WjG+BE1k5RBjONXTdS/7QBGr6TvP4ZK8MEOcBCyecezqv7yYVAxb+NNJOC5mzpns2crPKHomCyfa+AMGb172OOLw5qPgezBL3rmmSN2L9/RwmcizRvYTqTfPS7XtqzT3fr4/j6bz8ruE1adkwAieuOisqhFZt1K/utsQDTxhDw7TQqExaAvENjta738LDoTIxL4umng0b6HVPb/y8xfgLNQKfE48JaPKB80ixWvZGNZUHRbTebG29RDfvslI5jRsneQID/X0amEwhejbRL3u+WLkryp3TQK7s+/2W8FZT65icVEE66U8E4KNQ7r1HS18JzCMQZC3GT5uHveHxrFCkjx2nsiCeFPYS84WYsDap1jo=}
